# Streamlit Cloud Secrets Template
# Copy this content to your Streamlit Cloud app secrets section

[general]
API_BASE_URL = "https://prosora-sports-api.onrender.com"
ALERT_EMAIL = "akashdagar03@gmail.com"

[model]
PERFORMANCE_THRESHOLD = 0.65
CONFIDENCE_THRESHOLD = 0.7

[ui]
DEFAULT_LEAGUE = "E0"
DEFAULT_DAYS_AHEAD = 7
REFRESH_INTERVAL = 300

# Instructions for Streamlit Cloud:
# 1. Go to your app settings in Streamlit Cloud
# 2. Navigate to "Secrets" section
# 3. Copy and paste the above configuration
# 4. Save the secrets
# 5. Your app will automatically restart with the new configuration